### PR TITLE
Add retry logic to daemon if it fails to query the database

### PR DESCRIPTION
**Pull request by Tim020**
This will require whoever merges the code to run

```
pip install python-dateutil
```

wherever EncodeServ is run from

### CODE REVIEW

**Comment by Tim020** [comment]
Fixes #15

**Comment by mstratford** [comment]
I was about to fix this, let's give this a spin.

**Comment by mstratford** [comment]
Bad news, at this moment, it doesn't appear to start, and just dies silently.

**Comment by mstratford** [comment]
'''Traceback (most recent call last):
  File "server.py", line 22, in <module>
    daemon.start()
  File "/home/ystv/bin/EncodeSrv/encodesrv/daemon.py", line 107, in start
    self.run()
  File "/home/ystv/bin/EncodeSrv/encodesrv/__init__.py", line 94, in run
    self.thread_list.append(FFmpegJob().start())
AttributeError: 'EncodeSrvDaemon' object has no attribute 'thread_list' '''

**Comment by mstratford** [comment]
Seems to work as much as it did before and seems to recover after DB issues. #20 Is still an issue though.

**Pull request merged**
